//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaOtomasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankaOtomasyonEModel : DbContext
    {
        public BankaOtomasyonEModel()
            : base("name=BankaOtomasyonEModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HarcamaKategoriTbl> HarcamaKategoriTbls { get; set; }
        public virtual DbSet<HesapTbl> HesapTbls { get; set; }
        public virtual DbSet<KrediHarcamaDetayTbl> KrediHarcamaDetayTbls { get; set; }
        public virtual DbSet<KrediKartiDetayTbl> KrediKartiDetayTbls { get; set; }
        public virtual DbSet<KullaniciTbl> KullaniciTbls { get; set; }
        public virtual DbSet<RolTbl> RolTbls { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<HesapIslemDetay> HesapIslemDetays { get; set; }
    }
}
