//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class HarcamaKategoriTbl
    {
        public int KategoriId { get; set; }
        public string KategoriAdi { get; set; }
    }
}
