//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class KrediKartiDetayTbl
    {
        public int KartNo { get; set; }
        public Nullable<int> MusteriNo { get; set; }
        public string HesapKesTarih { get; set; }
        public string SonOdeme { get; set; }
        public string EkstreTarih { get; set; }
        public int Bakiye { get; set; }
    
        public virtual KullaniciTbl KullaniciTbl { get; set; }
    }
}
