//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KullaniciTbl()
        {
            this.HesapTbls = new HashSet<HesapTbl>();
            this.KrediKartiDetayTbls = new HashSet<KrediKartiDetayTbl>();
        }
    
        public int KullaniciId { get; set; }
        public string KullaniciAd { get; set; }
        public string Sifre { get; set; }
        public int RolId { get; set; }
        public string TcNo { get; set; }
        public string Isım { get; set; }
        public string Soyisim { get; set; }
        public string DogumTarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HesapTbl> HesapTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KrediKartiDetayTbl> KrediKartiDetayTbls { get; set; }
        public virtual RolTbl RolTbl { get; set; }
    }
}
